### ISSUE TITLE
Links from Identifier Search off by 4 lines.

### ISSUE THREAD

**Issue by mwelchuk** [free-electrons/elixir#9]
Searching for "SND_SOC_DAPM_POST_PMU" yields a number of hits:

http://elixir.free-electrons.com/linux/v4.10/ident/SND_SOC_DAPM_POST_PMU

Clicking on "line 217" from "include/sound/soc-dapm.h" appears to take me to line 217:

http://elixir.free-electrons.com/linux/v4.10/source/include/sound/soc-dapm.h#L217

However, the reference seems to be on line 213.

Scrolling to the top of the file, I can see that the line numbering isn't aligned with the lines of the file.

Viewing on Google Chrome, Version 56.0.2924.87 (64-bit), on Linux.

**Comment by michaelopdenacker** [comment]
Hi,

Thank you for testing Elixir!

However, I don't see this issue. SND_SOC_DAPM_POST_PMU is indeed used on line 217 (and defined elsewhere). 

I don't see the issue you're reporting about the mis-alignment of the file lines. 

Do you still observe this issue?

Thanks again,

Michael.

**Comment by mwelchuk** [comment]
Yes, I seem to be getting an offset between line numbering and the file contents.

This is using "Google Chrome	56.0.2924.87 (Official Build) (64-bit)"

![screenshot](https://cloud.githubusercontent.com/assets/6439246/25486681/e9910210-2b59-11e7-81b0-f2f86603194c.png)

**Comment by pokazef** [comment]
Thank you for the bug report and the screen capture.
I couldn't reproduce the problem, but can guess what's causing it: the line numbers and the source code are in separate table columns to allow for copy-pasting. In order to be aligned, they need to be rendered by the browser to the exact same height.
So my guess is that for some reason, your browser renders the line-number column shorter than the code column.
Am I correct in assuming that at the bottom of your page, line number 764 is actually next to the seventh-to-last line? If so, it confirms that the line-number column is shorter.
I could only test it on Chromium 57 for the moment, but I'll try it on Chrome 56 when I get the chance.

**Comment by mwelchuk** [comment]
I'm using Debian Jessie. Yes, there's an offset at the bottom as well:

![screenshot2](https://cloud.githubusercontent.com/assets/6439246/25495448/00a086c2-2b75-11e7-9f6c-6136751b1776.png)

**Comment by mwelchuk** [comment]
I've just updated to "Google Chrome	58.0.3029.81 (Official Build) (64-bit)", problem persists.

**Comment by pokazef** [comment]
OK, it seems your plain font is rendered in 16 pixels while your italic is rendered in 17 pixels. I've turned the italic style off for the comments, can you tell me if that takes care of your problem?

**Comment by mwelchuk** [comment]
Yes, that seems to be the issue.

**Comment by pokazef** [comment]
OK, thanks, I'll commit the change.

**Comment by tom3q** [comment]
I'm experiencing a similar problem on Chrome 59 and 60 on Ubuntu Trusty. It looks like for font-weight: bold or font-style: italic, the Ubuntu Mono font is fetched from a remote resource, while for some reason for regular variant the local file is used.

Since I don't need Ubuntu Mono in any of software I use, I just blacklisted the font in fontconfig:

```
<selectfont>
    <rejectfont>
        <pattern>
            <patelt name="family" >
                <string>Ubuntu Mono</string>
            </patelt>
        </pattern>
    </rejectfont>
</selectfont>
```

However, maybe there is a way to enforce remote font on CSS level for the site?

**Comment by pokazef** [comment]
> However, maybe there is a way to enforce remote font on CSS level for the site?

That's way out of my league, sorry. But maybe @zo could help?

A cleaner fix might be to force the rendering height of the line, regardless of the font.

An even cleaner fix would be to find a way to align the line numbers and the code explicitly, without relying on shaky HTML rendering assumptions.

For the record, the reason the page is structured this way (two independant text cells, one for the line numbers and one for the code) is to provide the ability to copy chunks of code without having the line numbers interfere.

I tried playing with the {-webkit-,-moz-,-ms-,}user-select CSS properties, but without much success. I'm open to suggestions at this point.
